### ISSUE TITLE
Slappers doesnt work correctly

### ISSUE THREAD

**Issue by MonoAdrian23** [HmmHmmmm/QuestPlugin#5]
When i click on a Slapper, nothing happens.
Please fix because this Plugin have no function.
Pocketmine Latest
Slapper Latest
QuestPlugin Latest

**Comment by HmmHmmmm** [comment]
Didn't see it at all, it works

**Comment by HmmHmmmm** [comment]
https://youtu.be/ATNHLwWdBbE

https://youtu.be/Jw-dtB5ATlo

**Comment by Adam1609** [comment]
@MonoAdrian23 did you have any of the disabled pvp protection or limiting gamemode? Cause that function will disable the hitting of slapper which make slappers dont work
